#服务的消费者配置文件
server:
  port: 9001
spring:
  application:
    name: server-consumer
#注册中心
eureka:
  client:
    service-url:
      #注册到Eureka的地址,多个使用","隔开
      defaultZone: http://127.0.0.1:7001/eureka/,http:127.0.0.1:7002/eureka/ 
      #获取服务地址列表间隔时间，默认30s
    registry-fetch-interval-seconds: 10
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 #单位毫秒
      circuitBreaker:
        errorThresholdPercentage: 50 #触发熔断错误比例阀值，默认是50%
        sleepWindowInMilliseconds: 10000 #熔断后休眠时长，默认值5秒
        requestVolumeThreshold: 10 #熔断触发最小请求次数，默认值是20
ribbon:
  ConnectTimeout: 1000 #连接超时时长
  ReadTimeout: 2000 #数据通信超时时长
  MaxAutoRetries: 0 #当前服务器的重试次数
  MaxAutoRetriesNextServer: 0 #重试多少次服务
  OkToRetryOnAllOperations: false #是否对所有的请求方式都重试
feign:
  hystrix:
    enabled: true #开启feign的熔断功能
  compression:
    request:
      enabled: true #开启请求压缩
      mime-types: text/html,application/xml,application/json #设置压缩的数据类型
      min-request-size: 2048 #设置触发压缩的大小下限
    response:
      enabled: true #开启响应压缩
logging:
  level:
    com.example: debug #开启日志信息 属性值为包名
