#服务的提供者1的配置文件
server:
  port: ${port:8001}
spring:
  application:
    name: TEST-PROVIDER  #服务名称，随便取
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.0.11/jfx-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
  #Redis配置
  redis:
    #Redis数据库索引（默认为0）
    database: 1
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间
    timeout: 1000
#注册中心
eureka:
  client:
    service-url:
      #注册到Eureka的地址
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/
  #服务续约
  instance:
    #定义服务续约任务的调用间隔时间，默认为30s,即每30s维护一个心跳用来持续告诉注册中心，“我还活着”，以防止注册中心的“剔除任务”
    #续约间隔，默认30s
    lease-renewal-interval-in-seconds: 5
    #定义服务失效的时间，默认为90s
    lease-expiration-duration-in-seconds: 90
    #更倾向使用IP地址，而不是host名
    prefer-ip-address: true
    #IP地址
    ip-address: 127.0.0.1
#Mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.provider.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      table-underline: true
      logic-delete-value: 1 # 数据库删除字段,1代表删除
      logic-not-delete-value: 0 # 0代表没删除
    banner: false
test:
  name: dlzzzzz
#是否开启swagger
swagger:
  enable: true
